// movie
export const SET_PREVIEW_LIST = "SET_PREVIEW_LIST";
export const SET_MOVIES_LIST = "SET_MOVIES_LIST";
export const SET_MOVIE_DETAILS = "SET_MOVIE_DETAILS";
export const SET_MOVIE_IMAGES = "SET_MOVIE_IMAGES";
export const SET_MOVIE_REVIEWS = "SET_MOVIE_REVIEWS";
export const SET_SEARCH_LIST = "SET_SEARCH_LIST";
